### ISSUE TITLE
При удалении компании вылетает ошибка 

### ISSUE THREAD

**Issue by GaynetdinovR** [ToltekPlus/steam#32]
При удалении компании вылетает ошибка из-за того что к ней привязаны игры
Вариант решения: 
Добавить компании видимость и при удалении менять видимость с 1 на 0, но саму компанию не удалять. Также не показывать игры от удалённой компании

**Comment by sergeybulankin** [comment]
Проблема решена.

Решение в коммите [https://github.com/ToltekPlus/steam/commit/cab23fc0cc2a95c8e3ca2bd6dad0a8856d7b1f79](url)

**Comment by sergeybulankin** [comment]
Решение 

https://github.com/ToltekPlus/steam/commit/cab23fc0cc2a95c8e3ca2bd6dad0a8856d7b1f79
